cursor_trail 10
cursor_trail_decay 0.1 0.3
cursor_shape block
shell_integration no-cursor
background #1a1110
foreground   #eeb996
cursor       #eeb996

color0       #0f1415
color8       #a68169
color1       #924A45
color9       #924A45
color2       #B05445
color10      #B05445
color3       #B0664C
color11      #B0664C
color4       #C95B44
color12      #C95B44
color5       #D66544
color13      #D66544
color6       #EA7344
color14      #EA7344
color7       #eeb996
color15      #eeb996

font_family JetBrainsMonoNL Nerd Font
font_size 12
