input-field {
	monitor =
	size = 250, 50
	outline_thickness = 2
	dots_size = 0.33
	dots_spacing = 0.15
	dots_center = true
	dots_rounding = -1
	fade_on_empty = false
	fade_timeout = 200
	hide_input = false

	inner_color = rgba(255,255,255,0.3)
	outer_color = rgba(255,255,255,0.4)
	font_color = rgba(250,250,250,0.85)

	placeholder_text = <i></i>

	position = 0, -100
	halign = center
	valign = center
 
  shadow_passes = 2
  shadow_size = 3
  shadow_color = rgba(200,200,200,0.75) 
}

background {
	monitor =
	path = ~/Pictures/wallpapers/wallhaven-xe85j3.jpg
	color = rgba(25, 20, 20, 1.0)
	blur_passes = 2
	blur_size = 5
}

label {
	monitor =
	text = cmd[update:1000] echo $TIME12
	font_size = 64
	color = rgba(250,250,250,0.85)
	font_family = JetBrainsMonoNL Nerd Font ExtraBold
  align = center
	valign = center
	position = 0, 160
  shadow_passes = 2
  shadow_size = 3
  shadow_color = rgba(200,200,200,0.75)
}

image {
	monitor =
	path = ~/Pictures/profile/114333810.jpg
	size = 100
	border_size = 2
	border_color = rgba(255,255,255,0.55)
	rounding = -1
	position = 0, 0

  shadow_passes = 1
  shadow_size = 2
  shadow_color = rgba(200,200,200,0.3)
}
